services:
  aerlift-qa:
    build: .
    image: aerlift-app:latest
    container_name: aerlift
    volumes:
      - .:/aerlift
      - "/Users/markcampmier/Library/Mobile Documents/com~apple~CloudDocs/aerlift/data:/aerlift/data"

    tty: true
    stdin_open: true
    command: ["snakemake", "--cores", "1", "--use-conda"]
