services:
  aerlift:
    build: .
    image: aerlift-app:latest
    container_name: aerlift
    volumes:
      - .:/aerlift
      - "${DATA_DIR}:/aerlift/data"

    tty: true
    stdin_open: true
    command: ["snakemake", "--cores", "1", "--use-conda"]
