name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: workflow/envs/python.yaml
        activate-environment: aerlift-python
        auto-activate-base: false
    - name: black
      shell: bash -el {0}
      run: black --check $(git ls-files '*.py')
    - name: flake8
      shell: bash -el {0}
      run: flake8 $(git ls-files '*.py')
    - name: pylint
      shell: bash -el {0}
      run: pylint $(git ls-files '*.py')
