name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: workflow/envs/python.yaml
        activate-environment: aerlift-python
        auto-activate-base: false
    - name: Analysing the code with pylint
      shell: bash -el {0}
      run: |
        pylint $(git ls-files '*.py')
